# Generated by Django 2.0.2 on 2018-03-07 13:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_comment', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('date', models.DateField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=100)),
                ('filepath', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('note_text', models.CharField(max_length=400)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateField(default=datetime.date.today)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('finish', models.BooleanField(default=False)),
                ('collaborators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('important', models.BooleanField(default=False)),
                ('finish', models.BooleanField(default=False)),
                ('collaborators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AddField(
            model_name='file',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
