# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date',
        ),
        migrations.AddField(
            model_name='file',
            name='filepath',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
