# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 16:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20171202_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('note_text', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateField(default=datetime.date.today, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='finished',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='note',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
