# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-23 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20171221_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='finished',
        ),
        migrations.AddField(
            model_name='project',
            name='finish',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
