# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-23 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20171223_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
