# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-17 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0012_note_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('important', models.BooleanField(default=False)),
                ('finish', models.BooleanField(default=False)),
                ('collaborators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
